### ISSUE TITLE
The podCIDR may unnecessary for kubelet-config.yaml

### ISSUE THREAD

**Issue by anr09** [e-minguez/kubernetes-the-hard-way-openstack#5]
According to the description:
--pod-cidr string                                                                                           The CIDR to use for pod IP addresses, only used in standalone mode.  In cluster mode, this is obtained from the master. 

It should only set for standalone Kubelets, and leave as empty by default for cluster mode.

**Comment by e-minguez** [comment]
> According to the description:
> --pod-cidr string The CIDR to use for pod IP addresses, only used in standalone mode. In cluster mode, this is obtained from the master.
> 
> It should only set for standalone Kubelets, and leave as empty by default for cluster mode.

Thanks for your comment!

Before removing it, it would be nice to confirm it works without it. Did you tested it without that flag?

**Comment by anr09** [comment]
> > According to the description:
> > --pod-cidr string The CIDR to use for pod IP addresses, only used in standalone mode. In cluster mode, this is obtained from the master.
> > It should only set for standalone Kubelets, and leave as empty by default for cluster mode.
> 
> Thanks for your comment!
> 
> Before removing it, it would be nice to confirm it works without it. Did you tested it without that flag?

Yes, it works!

Beacuse the options "--allocate-node-cidrs=true" is enabled in kube-controller-manager.service, the controller will allocate cidr for nodes.
This can be retrieved with below command after kubelet.service started:
`kubectl get nodes -o jsonpath='{.items[*].spec.podCIDR}'`

Furthermore, kube-route update podCIDR for CNI plugin in below priority:
-  anotation: "kube-router.io/pod-cidr"
-  node.Spec.PodCIDR

So set annotation for pod-cidr is duplicated. It's harmless but misleading.

**Comment by e-minguez** [comment]
Great!

I'll try to fix it, or if you want, please create a PR and I will review it :)

Thanks!!!
